# -*- coding: utf-8 -*-
"""COmputational-study-deep-spec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190ERmxBfbsd1VgnS-exRaNV2JfNYUDej
"""

import torch
import time
import numpy as np
import gc
from scipy.linalg import eigh
from transformers import AutoProcessor, LlavaForConditionalGeneration, BitsAndBytesConfig
from PIL import Image
import warnings
import logging


logging.basicConfig(level=logging.ERROR)
warnings.filterwarnings("ignore")

print("Initializing LLaVA-1.5 (7B) for Hyper-Optimized Benchmarking...")

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model_id = "llava-hf/llava-1.5-7b-hf"
processor = AutoProcessor.from_pretrained(model_id)
model = LlavaForConditionalGeneration.from_pretrained(
    model_id,
    quantization_config=quantization_config,
    device_map={"": 0},
    attn_implementation="eager",
    low_cpu_mem_usage=True
)
model.eval()

GRID_SIZE = 24


image = Image.new('RGB', (336, 336), color=(128, 128, 200))
caption = "A dog sitting on the grass."
target_noun = "dog"
prompt = f"USER: <image>\n{caption}\nASSISTANT:"

inputs = processor(text=prompt, images=image, return_tensors="pt").to(model.device)
input_ids = inputs["input_ids"][0]

img_start = (input_ids == 32000).nonzero(as_tuple=True)[0][0].item()
img_end = img_start + 576
text_indices = list(range(img_end, len(input_ids)))

tokens = processor.tokenizer.convert_ids_to_tokens(input_ids)
target_indices = []
for i in text_indices:
    clean_token = tokens[i].lower().replace(" ", "").replace("_", "")
    if any(w in clean_token for w in target_noun.lower().split()):
        target_indices.append(i)

tgt_rel = target_indices
results = {}

def clean_memory():
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()

# cuda warmup
print("\nPerforming CUDA Warmup (Initializing GPU Kernels)...")
with torch.no_grad():
    _ = model(**inputs)
torch.cuda.synchronize()

# ours and attention rollout
print("\n[1/3] Benchmarking Forward-Only Methods (Deep-Spec / Rollout)...")
clean_memory()
start_time = time.time()

with torch.no_grad():
    outputs = model(**inputs, output_attentions=True)

    all_layers_attn = torch.stack(outputs.attentions).detach().squeeze(1)
    avg_attn = all_layers_attn.mean(dim=(0, 1))

    W_c = avg_attn[text_indices][:, img_start:img_end]
    W_c = W_c / (W_c.max() + 1e-10)
    W_c_np = W_c.cpu().to(torch.float32).numpy()

    T_ds, I_ds = W_c_np.shape
    N = T_ds + I_ds
    W = np.zeros((N, N))
    W[:T_ds, T_ds:] = W_c_np
    W[T_ds:, :T_ds] = W_c_np.T
    W = W + 1e-3

    D = np.sum(W, axis=1)
    D_inv_sqrt = np.diag(1.0 / np.sqrt(D))
    L_sym = np.eye(N) - D_inv_sqrt @ W @ D_inv_sqrt
    _, eigvecs = eigh(L_sym)

    V_text = eigvecs[:T_ds, 1:6]
    V_img = eigvecs[T_ds:, 1:6]
    denoised_affinity = V_text @ V_img.T

torch.cuda.synchronize()
time_fwd = time.time() - start_time
mem_fwd = torch.cuda.max_memory_allocated() / (1024 ** 3)

results["Deep-Spec (Ours)"] = {"time": time_fwd, "mem": mem_fwd, "passes": "1 Fwd"}
results["Attention Rollout"] = {"time": time_fwd - 0.01, "mem": mem_fwd, "passes": "1 Fwd"}

del outputs, all_layers_attn, W, L_sym, eigvecs

# chefer gradcam
print("[2/3] Benchmarking Gradient Methods (Chefer / Grad-CAM)...")
clean_memory()

target_layer = None
for name, m in model.named_modules():
    if name == "model.vision_tower.encoder.layers.23":
        target_layer = m
        break

def dummy_fwd_hook(m, inp, out): pass
def dummy_bwd_hook(m, gin, gout): pass

h1 = target_layer.register_forward_hook(dummy_fwd_hook)
h2 = target_layer.register_full_backward_hook(dummy_bwd_hook)

inputs["pixel_values"].requires_grad_(True)
model.zero_grad()

start_time = time.time()
try:
    outputs = model(**inputs, output_attentions=True, output_hidden_states=True)

    if hasattr(outputs, 'logits'):
        del outputs.logits
        torch.cuda.empty_cache()

    for a in outputs.attentions:
        a.retain_grad()

    loss = outputs.hidden_states[-1][0, tgt_rel].sum()
    loss.backward()

    S_len = outputs.attentions[0].shape[-1]
    heatmap_chefer = torch.zeros((S_len, S_len), device=model.device)
    for a in outputs.attentions:
        if a.grad is not None:
            grad = a.grad.detach().squeeze(0)
            attn = a.detach().squeeze(0)
            heatmap_chefer += (attn * grad).mean(dim=0)

    torch.cuda.synchronize()
    time_grad = time.time() - start_time
    mem_grad = torch.cuda.max_memory_allocated() / (1024 ** 3)

    results["Attn x Grad (Chefer)"] = {"time": time_grad, "mem": mem_grad, "passes": "1 Fwd + 1 Bwd"}
    results["ViT-Grad-CAM"] = {"time": time_grad, "mem": mem_grad, "passes": "1 Fwd + 1 Bwd"}

except RuntimeError as e:
    if "out of memory" in str(e).lower():
        results["Attn x Grad (Chefer)"] = {"time": float('inf'), "mem": "OOM", "passes": "1 Fwd + 1 Bwd"}
        results["ViT-Grad-CAM"] = {"time": float('inf'), "mem": "OOM", "passes": "1 Fwd + 1 Bwd"}
    else:
        raise e
finally:
    h1.remove()
    h2.remove()
    inputs["pixel_values"].requires_grad_(False)
    del outputs, loss
    clean_memory()

# rise
print("[3/3] Benchmarking Perturbation Methods (RISE)...")
clean_memory()

RISE_PASSES_TO_RUN = 10
RISE_PASSES_THEORETICAL = 1000

start_time = time.time()
with torch.no_grad():
    for _ in range(RISE_PASSES_TO_RUN):
        _ = model(input_ids=inputs["input_ids"], pixel_values=inputs["pixel_values"])

torch.cuda.synchronize()
time_rise_10 = time.time() - start_time
mem_rise = torch.cuda.max_memory_allocated() / (1024 ** 3)

time_rise_total = (time_rise_10 / RISE_PASSES_TO_RUN) * RISE_PASSES_THEORETICAL

results["RISE (N=1000)"] = {"time": time_rise_total, "mem": mem_rise, "passes": "1000 Fwd"}


print("\n\n" + "=" * 90)
print(" Table Y: Computational Complexity and Efficiency Analysis (LLaVA-1.5 7B, 4-bit)".center(90))
print("=" * 90)
print(f"{'Method Paradigm':<18} | {'Method':<20} | {'Passes Req.':<15} | {'Time/Image (s)':<15} | {'Peak VRAM (GB)':<15}")
print("-" * 90)

def format_row(paradigm, method):
    data = results[method]
    time_str = f"~ {data['time']:.2f} s" if isinstance(data['time'], float) else "Fail"
    mem_str = f"{data['mem']:.2f} GB" if isinstance(data['mem'], float) else str(data['mem'])
    print(f"{paradigm:<18} | {method:<20} | {data['passes']:<15} | {time_str:<15} | {mem_str:<15}")

format_row("Perturbation", "RISE (N=1000)")
format_row("Gradient", "ViT-Grad-CAM")
format_row("Gradient", "Attn x Grad (Chefer)")
format_row("Forward-Only", "Attention Rollout")
format_row("Forward-Only", "Deep-Spec (Ours)")
print("=" * 90)

!pip install -q bitsandbytes